[package]
name = "AnimeSwapV1"
version = "1.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "83641d3f083762f31700060e5e95fbb1cbc28bf0" }
LPCoin = { local = "../LPCoin" }
LPResourceAccount = { local = "../LPResourceAccount" }
U256 = { local = "../u256" }
UQ64x64 = { local = "../uq64x64" }

[addresses]
SwapDeployer = "_"
uq64x64 = "_"
u256 = "_"
ResourceAccountDeployer = "0xf63ca86b418c320f5e1b57cc3962c67c51dab90acb5846b3fa49af6120c8caf7"
